# This file is used by Acquia Pipelines continuous integration.
version: 1.1.0
services:
  - mysql
  - php:
      version: 7.3

events:
  build:
    steps:
      - setup:
          type: script
          script:
            - set -x
            - composer validate --no-check-all --ansi
            - composer install
